//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotaqWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanDetail
    {
        public int LoanDetailsId { get; set; }
        public string PhoneNumber { get; set; }
        public string LoanStatus { get; set; }
        public decimal LoanAmount { get; set; }
        public int InterestRate { get; set; }
        public decimal ProcessFee { get; set; }
        public decimal LatePaymentCharges { get; set; }
        public string Duration { get; set; }
        public System.DateTime DueDate { get; set; }
        public string PaymentReferenceNo { get; set; }
        public string LoanTransactionNo { get; set; }
        public Nullable<System.DateTime> DateofLoan { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual Register Register { get; set; }
    }
}
