//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotaqWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentsId { get; set; }
        public string LoanAmount { get; set; }
        public string Intrest { get; set; }
        public string PhoneNumber { get; set; }
        public string ProessingFee { get; set; }
        public string DueDate { get; set; }
        public string PaymentStatus { get; set; }
    
        public virtual Register Register { get; set; }
    }
}
