//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotaqWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaySlipDocument
    {
        public string PhoneNumber { get; set; }
        public string PaySlipUrl { get; set; }
        public int PayslipId { get; set; }
    
        public virtual Register Register { get; set; }
    }
}
