//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotaqWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalDetail
    {
        public int PersonalDetailsId { get; set; }
        public string PhoneNumber { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string DOB { get; set; }
        public string MaritalStatus { get; set; }
        public string CurrentAddress { get; set; }
    
        public virtual Register Register { get; set; }
    }
}
