//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotaqWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfessionalDetail
    {
        public int ProfessionalDetailsId { get; set; }
        public string PhoneNumber { get; set; }
        public string CompanyName { get; set; }
        public Nullable<decimal> MonthlyIncome { get; set; }
        public string YearOfExperience { get; set; }
        public Nullable<decimal> CurrentEMI { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyEmailId { get; set; }
    
        public virtual Register Register { get; set; }
    }
}
