//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotaqWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceDetail
    {
        public int ReferenceId { get; set; }
        public string PhoneNumber { get; set; }
        public string Reference1 { get; set; }
        public string ReferenceName1 { get; set; }
        public string Reference2 { get; set; }
        public string ReferenceName2 { get; set; }
    
        public virtual Register Register { get; set; }
    }
}
