//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotaqWebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GTLOANEntities : DbContext
    {
        public GTLOANEntities()
            : base("name=GTLOANEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdharCardDocument> AdharCardDocuments { get; set; }
        public virtual DbSet<AdminLogin> AdminLogins { get; set; }
        public virtual DbSet<BankstatementDocument> BankstatementDocuments { get; set; }
        public virtual DbSet<BasicDetail> BasicDetails { get; set; }
        public virtual DbSet<ContactUser> ContactUsers { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<IDCardDocument> IDCardDocuments { get; set; }
        public virtual DbSet<LoanDetail> LoanDetails { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<OneTimeFee> OneTimeFees { get; set; }
        public virtual DbSet<PANCardDocument> PANCardDocuments { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PaySlipDocument> PaySlipDocuments { get; set; }
        public virtual DbSet<PersonalDetail> PersonalDetails { get; set; }
        public virtual DbSet<ProfessionalDetail> ProfessionalDetails { get; set; }
        public virtual DbSet<ReferenceDetail> ReferenceDetails { get; set; }
        public virtual DbSet<Register> Registers { get; set; }
        public virtual DbSet<SelfieDocument> SelfieDocuments { get; set; }
        public virtual DbSet<SignatureDocument> SignatureDocuments { get; set; }
        public virtual DbSet<UserContact> UserContacts { get; set; }
    }
}
